apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-client
  template:
    metadata:
      labels:
        app: istio-client
    spec:
      containers:
        - name: istio-client
          image: ethan510010/istio-client:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: SERVER_HOST
              value: "istio-server"
            - name: SERVER_PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: istio-client
spec:
  type: ClusterIP
  selector:
    app: istio-client
  ports:
  - name: http-3000 # 端口名加上了http前綴
    port: 3000
    targetPort: 3000