apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-server
spec:
  hosts:
    - istio-server
  http:
  - fault:
      abort:
        percentage:
          value: 80.0
        httpStatus: 500
    route:
    - destination:
        host: istio-server


