apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-server
spec:
  hosts:
    - istio-server
  http:
  - route:
    - destination:
        host: istio-server
        subset: v1
      weight: 80
    - destination:
        host: istio-server
        subset: v2
      weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-server
spec:
  host: istio-server
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2